export const actionTypes = {
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    SET_FIRST_AUTH: "SET_FIRST_AUTH",
    SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    SET_MY_PRODUCTS: "SET_MY_PRODUCTS"
}